name: Publish and Package

on:
  push:
    branches: [ main ]

    # Required permissions for release creation and npm publish
permissions:
  contents: write
  packages: write
  actions: read
  
jobs:
  publish-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed for version bumping

    # Automatic version bumping based on commit messages
    - name: Bump version
      uses: phips28/gh-action-bump-version@master
      id: bump-version
      with:
        tag-prefix: 'v'
        skip-tag: true  # We'll create the tag in the release step
        skip-commit: true  # Don't create commit
        skip-push: true    # Don't push changes
        default-build-metadata: 'ci.${{ github.run_number }}'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci
      
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
    - name: Install pkg
      run: npm install pkg
      
    - name: Package application
      run: |  
        mkdir -p assets
        npx pkg . --output ./assets/naukri-ninja.exe --targets node18-win-x64
      
    # Create GitHub release with the executable
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: success()
      with:
        tag_name: v${{ steps.bump-version.outputs.new_version }}
        name: "Release v${{ steps.bump-version.outputs.new_version }}"
        body: |
          Automated release for Naukri Ninja
          Version: ${{ steps.bump-version.outputs.new_version }}
          Build: ${{ github.run_number }}
          Changes:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false
        files: |
          assets/naukri-ninja.exe

    - name: Upload executable artifact
      uses: actions/upload-artifact@v4
      with:
        name: naukri-ninja-v${{ steps.bump-version.outputs.new_version }}
        path: assets/naukri-ninja.exe
        retention-days: 7
