name: Publish and Package

on:
  push:
    branches: [ main ]
    paths:
      - 'package.json'

jobs:
  publish-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
      
    - name: Install dependencies
      run: npm ci
      
    # Explicitly install pkg if not in package.json
    - name: Install pkg
      run: npm install pkg
      
    - name: Publish to npm
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
    - name: Package application
      run: |  
        mkdir -p assets
        npx pkg . --output ./assets/naukri-ninja.exe --targets node18-win-x64
      
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: executable
        path: assets/naukri-ninja.exe